# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0d1f1dd71a84264a3e47d6fc2505f892aeb97921f45b1b78d1483a9fe41d732f0e150d888f632eec5927390700d585ed6c574740d5312477e429d5f91f7fdc0

test:
  secret_key_base: 4217c3c38d43e55e4b87030283f97d7e2e35061cfdbd050d389f171e401dc4a8acdb3e694debfe9f773c3b480fff4d5bc4454246c6c5248019355dcbe9365ebc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
